<a href="https://colab.research.google.com/github/amey-raj/Power-consumption/blob/main/Decision%20Tree%20Regression/Decision_Tree_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Importing the libraries**

In [6]:
import numpy as np 
import matplotlib.pyplot as plt 
import pandas as pd

In [7]:
dataset = pd.read_csv(r'Tetouan City power consumption.csv')
X = dataset.iloc[:, 1:6].values
y1 = dataset.iloc[:, 6].values
y2 = dataset.iloc[:, 7].values
y3 = dataset.iloc[:, 8].values

In [8]:
print(y3)

[20240.96386 20131.08434 19668.43373 ... 13806.48259 13512.60504
 13345.4982 ]


**Splitting the dataset into the Training set and Test set**

In [9]:
from sklearn.model_selection import train_test_split
X_train1, X_test1, y_train1, y_test1 = train_test_split(X, y1, test_size = 0.2, random_state = 0)
X_train2, X_test2, y_train2, y_test2 = train_test_split(X, y2, test_size = 0.2, random_state = 0)
X_train3, X_test3, y_train3, y_test3 = train_test_split(X, y3, test_size = 0.2, random_state = 0)

**Training Model**

In [10]:
from sklearn.tree import DecisionTreeRegressor
regressor1 = DecisionTreeRegressor(random_state = 0)
regressor1.fit(X_train1, y_train1)

DecisionTreeRegressor(random_state=0)

In [11]:
regressor2 = DecisionTreeRegressor(random_state = 0)
regressor2.fit(X_train2, y_train2)

DecisionTreeRegressor(random_state=0)

In [12]:
regressor3 = DecisionTreeRegressor(random_state = 0)
regressor3.fit(X_train3, y_train3)

DecisionTreeRegressor(random_state=0)

**Predicting the Test set results**

In [13]:
y_pred1 = regressor1.predict(X_test1)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred1.reshape(len(y_pred1),1), y_test1.reshape(len(y_test1),1)),1))

[[24654.83 27782.78]
 [31517.34 26386.35]
 [34068.45 27506.55]
 ...
 [39218.36 38639.21]
 [30542.26 36790.9 ]
 [42522.71 25267.12]]


In [14]:
y_pred2 = regressor2.predict(X_test2)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred2.reshape(len(y_pred2),1), y_test2.reshape(len(y_test2),1)),1))

[[16446.99 17191.68]
 [17731.12 17887.97]
 [15672.35 15537.63]
 ...
 [20206.81 23650.77]
 [17607.74 22753.94]
 [16974.53 15497.87]]


In [15]:
y_pred3 = regressor3.predict(X_test3)
np.set_printoptions(precision=2) 
print(np.concatenate((y_pred3.reshape(len(y_pred3),1), y_test3.reshape(len(y_test3),1)),1))

[[13408.62 21184.98]
 [22262.76 13375.81]
 [24941.94 13967.56]
 ...
 [16924.37 20276.6 ]
 [24034.14 13049.  ]
 [23329.45 15450.69]]


**Evaluating the Model Performance**

In [16]:
from sklearn.metrics import r2_score
r2_score(y_test1, y_pred1)

0.15821353353540746

In [17]:
r2_score(y_test2, y_pred2)

0.11741900391107751

In [18]:
r2_score(y_test3, y_pred3)

0.44613570175547723