<a href="https://colab.research.google.com/github/amey-raj/Power-consumption/blob/main/Support%20Vector%20Regression/Support_Vector_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Importing the libraries**

In [5]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [6]:
dataset = pd.read_csv(r'Tetouan City power consumption.csv')
X = dataset.iloc[:, 1:6].values
y1 = dataset.iloc[:, 6].values
y2 = dataset.iloc[:, 7].values
y3 = dataset.iloc[:, 8].values

In [7]:
print(y3)

[20240.96386 20131.08434 19668.43373 ... 13806.48259 13512.60504
 13345.4982 ]


**Splitting the dataset into the Training set and Test set**

In [8]:
from sklearn.model_selection import train_test_split
X_train1, X_test1, y_train1, y_test1 = train_test_split(X, y1, test_size = 0.2, random_state = 0)
X_train2, X_test2, y_train2, y_test2 = train_test_split(X, y2, test_size = 0.2, random_state = 0)
X_train3, X_test3, y_train3, y_test3 = train_test_split(X, y3, test_size = 0.2, random_state = 0)

**Scaling Data**

In [9]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
sc_y = StandardScaler()
X_train1 = sc_X.fit_transform(X_train1)
y_train1 = sc_y.fit_transform(y_train1.reshape(-1, 1))

In [10]:
X_train2 = sc_X.fit_transform(X_train2)
y_train2 = sc_y.fit_transform(y_train2.reshape(-1, 1))

In [11]:
X_train3 = sc_X.fit_transform(X_train3)
y_train3 = sc_y.fit_transform(y_train3.reshape(-1, 1))

**Training Model**

In [12]:
from sklearn.svm import SVR
regressor1 = SVR(kernel = 'rbf')
regressor1.fit(X_train1, y_train1)
regressor2 = SVR(kernel = 'rbf')
regressor2.fit(X_train2, y_train2)
regressor3 = SVR(kernel = 'rbf')
regressor3.fit(X_train3, y_train3)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR()

**Predicting the Test set results**

In [13]:
y_pred1 = sc_y.inverse_transform(regressor1.predict(sc_X.transform(X_test1)).reshape(-1,1))
np.set_printoptions(precision=2)
print(np.concatenate((y_pred1.reshape(len(y_pred1),1), y_test1.reshape(len(y_test1),1)),1))

[[13165.22 27782.78]
 [17382.2  26386.35]
 [22207.57 27506.55]
 ...
 [17536.67 38639.21]
 [19655.84 36790.9 ]
 [14836.8  25267.12]]


In [14]:
y_pred2 = sc_y.inverse_transform(regressor2.predict(sc_X.transform(X_test2)).reshape(-1,1))
np.set_printoptions(precision=2)
print(np.concatenate((y_pred2.reshape(len(y_pred2),1), y_test2.reshape(len(y_test2),1)),1))

[[12034.74 17191.68]
 [16957.73 17887.97]
 [20826.41 15537.63]
 ...
 [17158.41 23650.77]
 [18989.4  22753.94]
 [16736.34 15497.87]]


In [15]:
y_pred3 = sc_y.inverse_transform(regressor3.predict(sc_X.transform(X_test3)).reshape(-1,1))
np.set_printoptions(precision=2) 
print(np.concatenate((y_pred3.reshape(len(y_pred3),1), y_test3.reshape(len(y_test3),1)),1))

[[13241.2  21184.98]
 [18155.42 13375.81]
 [21328.4  13967.56]
 ...
 [16578.1  20276.6 ]
 [15073.75 13049.  ]
 [15624.85 15450.69]]


**Evaluating the Model Performance**

In [16]:
from sklearn.metrics import r2_score
r2_score(y_test1, y_pred1)

-4.216025463029749

In [17]:
r2_score(y_test2, y_pred2)

-0.29798783077792557

In [18]:
r2_score(y_test3, y_pred3)

0.49280938272883823