<a href="https://colab.research.google.com/github/amey-raj/Power-consumption/blob/main/Polynomial%20Regression/Polynomial_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Importing the libraries**

In [3]:
import numpy as np 
import matplotlib.pyplot as plt 
import pandas as pd

In [4]:
dataset = pd.read_csv('Tetouan City power consumption.csv')
X = dataset.iloc[:, 1:6].values
y1 = dataset.iloc[:, 6].values
y2 = dataset.iloc[:, 7].values
y3 = dataset.iloc[:, 8].values

In [5]:
print(y3)

[20240.96386 20131.08434 19668.43373 ... 13806.48259 13512.60504
 13345.4982 ]


**Splitting the dataset into the Training set and Test set**

In [6]:
from sklearn.model_selection import train_test_split
X_train1, X_test1, y_train1, y_test1 = train_test_split(X, y1, test_size = 0.2, random_state = 0)
X_train2, X_test2, y_train2, y_test2 = train_test_split(X, y2, test_size = 0.2, random_state = 0)
X_train3, X_test3, y_train3, y_test3 = train_test_split(X, y3, test_size = 0.2, random_state = 0)

**Training Model**

In [7]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
poly_reg1 = PolynomialFeatures(degree = 4)
X_poly1 = poly_reg1.fit_transform(X_train1)
regressor1 = LinearRegression()
regressor1.fit(X_poly1, y_train1)

LinearRegression()

In [8]:
poly_reg2 = PolynomialFeatures(degree = 4)
X_poly2 = poly_reg2.fit_transform(X_train2)
regressor2 = LinearRegression()
regressor2.fit(X_poly2, y_train2)

LinearRegression()

In [9]:
poly_reg3 = PolynomialFeatures(degree = 4)
X_poly3 = poly_reg3.fit_transform(X_train3)
regressor3 = LinearRegression()
regressor3.fit(X_poly3, y_train3)

LinearRegression()

**Predicting the Test set results**

In [10]:
y_pred1 = regressor1.predict(poly_reg1.transform(X_test1))
np.set_printoptions(precision=2)
print(np.concatenate((y_pred1.reshape(len(y_pred1),1), y_test1.reshape(len(y_test1),1)),1))

[[28099.1  27782.78]
 [33807.33 26386.35]
 [36152.1  27506.55]
 ...
 [30846.95 38639.21]
 [33987.17 36790.9 ]
 [31291.11 25267.12]]


In [11]:
y_pred2 = regressor2.predict(poly_reg2.transform(X_test2))
np.set_printoptions(precision=2)
print(np.concatenate((y_pred2.reshape(len(y_pred2),1), y_test2.reshape(len(y_test2),1)),1))

[[17074.   17191.68]
 [21261.35 17887.97]
 [23012.97 15537.63]
 ...
 [19860.65 23650.77]
 [22044.07 22753.94]
 [21320.67 15497.87]]


In [12]:
y_pred3 = regressor3.predict(poly_reg3.transform(X_test3))
np.set_printoptions(precision=2) 
print(np.concatenate((y_pred3.reshape(len(y_pred3),1), y_test3.reshape(len(y_test3),1)),1))

[[14348.43 21184.98]
 [19196.94 13375.81]
 [20748.09 13967.56]
 ...
 [16714.13 20276.6 ]
 [15998.66 13049.  ]
 [16934.06 15450.69]]


**Evaluating the Model Performance**

In [13]:
from sklearn.metrics import r2_score
r2_score(y_test1, y_pred1)

0.2931009241934657

In [14]:
r2_score(y_test2, y_pred2)

0.2775232818780108

In [15]:
r2_score(y_test3, y_pred3)

0.5015692106804766