<a href="https://colab.research.google.com/github/amey-raj/Power-consumption/blob/main/Random%20Forest%20Regression/Random_Forest_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Importing the libraries**

In [3]:
import numpy as np 
import matplotlib.pyplot as plt 
import pandas as pd

In [4]:
dataset = pd.read_csv(r'Tetouan City power consumption.csv')
X = dataset.iloc[:, 1:6].values
y1 = dataset.iloc[:, 6].values
y2 = dataset.iloc[:, 7].values
y3 = dataset.iloc[:, 8].values

In [5]:
print(y3)

[20240.96386 20131.08434 19668.43373 ... 13806.48259 13512.60504
 13345.4982 ]


**Splitting the dataset into the Training set and Test set**

In [6]:
from sklearn.model_selection import train_test_split
X_train1, X_test1, y_train1, y_test1 = train_test_split(X, y1, test_size = 0.2, random_state = 0)
X_train2, X_test2, y_train2, y_test2 = train_test_split(X, y2, test_size = 0.2, random_state = 0)
X_train3, X_test3, y_train3, y_test3 = train_test_split(X, y3, test_size = 0.2, random_state = 0)

**Training Model**

In [7]:
from sklearn.ensemble import RandomForestRegressor
regressor1 = RandomForestRegressor(n_estimators = 10, random_state = 0)
regressor1.fit(X_train1, y_train1)

RandomForestRegressor(n_estimators=10, random_state=0)

In [8]:
regressor2 = RandomForestRegressor(n_estimators = 10, random_state = 0)
regressor2.fit(X_train2, y_train2)

RandomForestRegressor(n_estimators=10, random_state=0)

In [9]:
regressor3 = RandomForestRegressor(n_estimators = 10, random_state = 0)
regressor3.fit(X_train3, y_train3)

RandomForestRegressor(n_estimators=10, random_state=0)

**Predicting the Test set results**

In [10]:
y_pred1 = regressor1.predict(X_test1)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred1.reshape(len(y_pred1),1), y_test1.reshape(len(y_test1),1)),1))

[[29676.72 27782.78]
 [30332.85 26386.35]
 [32621.21 27506.55]
 ...
 [32483.53 38639.21]
 [33117.25 36790.9 ]
 [30980.52 25267.12]]


In [11]:
y_pred2 = regressor2.predict(X_test2)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred2.reshape(len(y_pred2),1), y_test2.reshape(len(y_test2),1)),1))

[[16898.3  17191.68]
 [17895.18 17887.97]
 [19119.08 15537.63]
 ...
 [20348.95 23650.77]
 [23288.12 22753.94]
 [20394.37 15497.87]]


In [12]:
y_pred3 = regressor3.predict(X_test3)
np.set_printoptions(precision=2) 
print(np.concatenate((y_pred3.reshape(len(y_pred3),1), y_test3.reshape(len(y_test3),1)),1))

[[18550.02 21184.98]
 [15750.5  13375.81]
 [17920.4  13967.56]
 ...
 [15139.59 20276.6 ]
 [16885.68 13049.  ]
 [17998.59 15450.69]]


**Evaluating the Model Performance**

In [13]:
from sklearn.metrics import r2_score
r2_score(y_test1, y_pred1)

0.5310165270393037

In [14]:
r2_score(y_test2, y_pred2)

0.5119369305109509

In [15]:
r2_score(y_test3, y_pred3)

0.6856781650527263