<a href="https://colab.research.google.com/github/amey-raj/Power-consumption/blob/main/Linear%20Regression/Linear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Importing the libraries**

In [11]:
import numpy as np 
import matplotlib.pyplot as plt 
import pandas as pd

In [12]:
dataset = pd.read_csv(r'Tetouan City power consumption.csv')
X = dataset.iloc[:, 1:6].values
y1 = dataset.iloc[:, 6].values
y2 = dataset.iloc[:, 7].values
y3 = dataset.iloc[:, 8].values

In [13]:
print(y3)

[20240.96386 20131.08434 19668.43373 ... 13806.48259 13512.60504
 13345.4982 ]


**Splitting the dataset into the Training set and Test set**

In [14]:
from sklearn.model_selection import train_test_split
X_train1, X_test1, y_train1, y_test1 = train_test_split(X, y1, test_size = 0.2, random_state = 0)
X_train2, X_test2, y_train2, y_test2 = train_test_split(X, y2, test_size = 0.2, random_state = 0)
X_train3, X_test3, y_train3, y_test3 = train_test_split(X, y3, test_size = 0.2, random_state = 0)

**Training Model**

In [15]:
from sklearn.linear_model import LinearRegression
regressor1 = LinearRegression()
regressor1.fit(X_train1, y_train1)

LinearRegression()

In [16]:
regressor2 = LinearRegression()
regressor2.fit(X_train2, y_train2)

LinearRegression()

In [17]:
regressor3 = LinearRegression()
regressor3.fit(X_train3, y_train3)

LinearRegression()

**Predicting the Test set results**

In [18]:
y_pred1 = regressor1.predict(X_test1)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred1.reshape(len(y_pred1),1), y_test1.reshape(len(y_test1),1)),1))

[[31881.1  27782.78]
 [33114.89 26386.35]
 [36506.36 27506.55]
 ...
 [32854.8  38639.21]
 [36093.38 36790.9 ]
 [30705.1  25267.12]]


In [19]:
y_pred2 = regressor2.predict(X_test2)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred2.reshape(len(y_pred2),1), y_test2.reshape(len(y_test2),1)),1))

[[20391.16 17191.68]
 [21638.54 17887.97]
 [23917.57 15537.63]
 ...
 [20902.47 23650.77]
 [23640.76 22753.94]
 [20351.72 15497.87]]


In [20]:
y_pred3 = regressor3.predict(X_test3)
np.set_printoptions(precision=2) 
print(np.concatenate((y_pred3.reshape(len(y_pred3),1), y_test3.reshape(len(y_test3),1)),1))

[[19468.28 21184.98]
 [20330.76 13375.81]
 [21022.54 13967.56]
 ...
 [18205.06 20276.6 ]
 [21111.09 13049.  ]
 [16058.58 15450.69]]


**Evaluating the Model Performance**

In [21]:
from sklearn.metrics import r2_score
r2_score(y_test1, y_pred1)

0.21203137397209093

In [22]:
r2_score(y_test2, y_pred2)

0.1744958337299286

In [23]:
r2_score(y_test3, y_pred3)

0.28433541477558044